{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2023-3915",
	"modified": "2024-11-27T19:40:48.342Z",
	"published": "2024-03-06T11:02:39.174Z",
	"aliases": [
		"CVE-2023-3915"
	],
	"details": "An issue has been discovered in GitLab EE affecting all versions starting from 16.1 before 16.1.5, all versions starting from 16.2 before 16.2.5, all versions starting from 16.3 before 16.3.1. If an external user is given an owner role on any group, that external user may escalate their privileges on the instance by creating a service account in that group. This service account is not classified as external and may be used to access internal projects.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "16.1.0"
						},
						{
							"fixed": "16.1.5"
						},
						{
							"introduced": "16.2.0"
						},
						{
							"fixed": "16.2.5"
						},
						{
							"introduced": "16.3.0"
						},
						{
							"fixed": "16.3.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2023-3915.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/417664"
		},
		{
			"type": "WEB",
			"url": "https://hackerone.com/reports/2040834"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:16.3.0:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:16.3.0:*:*:*:enterprise:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
