{
	"schema_version": "1.6.0",
	"id": "BIT-mlflow-2024-27132",
	"modified": "2024-07-18T07:56:34.499Z",
	"published": "2024-03-31T18:21:50.638Z",
	"aliases": [
		"CVE-2024-27132",
		"GHSA-6749-m5cp-6cg7"
	],
	"details": "Insufficient sanitization in MLflow leads to XSS when running an untrusted recipe.This issue leads to a client-side RCE when running an untrusted recipe in Jupyter Notebook.The vulnerability stems from lack of sanitization over template variables.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "mlflow",
				"purl": "pkg:bitnami/mlflow"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.10.0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/mlflow/BIT-mlflow-2024-27132.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/mlflow/mlflow/pull/10873"
		},
		{
			"type": "WEB",
			"url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-recipe-xss-jfsa-2024-000631930/"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:lfprojects:mlflow:*:*:*:*:*:*:*:*",
			"cpe:2.3:a:lfprojects:mlflow:*:*:*:*:*:python:*:*"
		],
		"severity": "High"
	}
}
