{
	"schema_version": "1.6.0",
	"id": "BIT-gitlab-2020-6832",
	"modified": "2025-01-17T15:26:01.971Z",
	"published": "2024-03-06T11:21:05.852Z",
	"aliases": [
		"CVE-2020-6832"
	],
	"details": "An issue was discovered in GitLab Enterprise Edition (EE) 8.9.0 through 12.6.1. Using the project import feature, it was possible for someone to obtain issues from private projects.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitlab",
				"purl": "pkg:bitnami/gitlab"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "8.9.0"
						},
						{
							"last_affected": "12.6.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2020-6832.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://about.gitlab.com/blog/categories/releases/"
		},
		{
			"type": "WEB",
			"url": "https://about.gitlab.com/releases/2020/01/13/critical-security-release-gitlab-12-dot-6-dot-4-released/"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
			"cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
		],
		"severity": "Medium"
	}
}
