{
	"schema_version": "1.6.0",
	"id": "BIT-tensorflow-2020-15265",
	"modified": "2024-11-27T19:40:48.342Z",
	"published": "2024-03-06T11:20:21.200Z",
	"aliases": [
		"CVE-2020-15265",
		"GHSA-rrfp-j2mp-hq9c",
		"PYSEC-2020-138",
		"PYSEC-2020-295",
		"PYSEC-2020-330"
	],
	"details": "In Tensorflow before version 2.4.0, an attacker can pass an invalid `axis` value to `tf.quantization.quantize_and_dequantize`. This results in accessing a dimension outside the rank of the input tensor in the C++ kernel implementation. However, dim_size only does a DCHECK to validate the argument and then uses it to access the corresponding element of an array. Since in normal builds, `DCHECK`-like macros are no-ops, this results in segfault and access out of bounds of the array. The issue is patched in eccb7ec454e6617738554a255d77f08e60ee0808 and TensorFlow 2.4.0 will be released containing the patch. TensorFlow nightly packages after this commit will also have the issue resolved.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "tensorflow",
				"purl": "pkg:bitnami/tensorflow"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.4.0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/tensorflow/BIT-tensorflow-2020-15265.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/tensorflow/tensorflow/commit/eccb7ec454e6617738554a255d77f08e60ee0808"
		},
		{
			"type": "WEB",
			"url": "https://github.com/tensorflow/tensorflow/issues/42105"
		},
		{
			"type": "WEB",
			"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-rrfp-j2mp-hq9c"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:google:tensorflow:*:*:*:*:-:*:*:*"
		],
		"severity": "Medium"
	}
}
