{
	"schema_version": "1.6.0",
	"id": "BIT-gitea-2022-38183",
	"modified": "2024-06-10T17:13:35.618203Z",
	"published": "2024-03-06T10:52:48.810Z",
	"aliases": [
		"CVE-2022-38183",
		"GHSA-fhv8-m4j4-cww2",
		"GO-2024-2769"
	],
	"details": "In Gitea before 1.16.9, it was possible for users to add existing issues to projects. Due to improper access controls, an attacker could assign any issue to any project in Gitea (there was no permission check for fetching the issue). As a result, the attacker would get access to private issue titles.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "gitea",
				"purl": "pkg:bitnami/gitea"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.16.9"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/gitea/BIT-gitea-2022-38183.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://blog.gitea.io/2022/07/gitea-1.16.9-is-released/"
		},
		{
			"type": "WEB",
			"url": "https://herolab.usd.de/security-advisories/usd-2022-0015/"
		},
		{
			"type": "WEB",
			"url": "https://security.gentoo.org/glsa/202210-14"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:gitea:gitea:*:*:*:*:*:*:*:*"
		],
		"severity": "Medium"
	}
}
