{
	"schema_version": "1.6.0",
	"id": "BIT-pytorch-2022-45907",
	"modified": "2024-03-06T11:25:28.861Z",
	"published": "2024-03-06T11:02:51.602Z",
	"aliases": [
		"CVE-2022-45907",
		"GHSA-47fc-vmwq-366v",
		"PYSEC-2022-43015"
	],
	"details": "In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.",
	"affected": [
		{
			"package": {
				"ecosystem": "Bitnami",
				"name": "pytorch",
				"purl": "pkg:bitnami/pytorch"
			},
			"severity": [
				{
					"type": "CVSS_V3",
					"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
				}
			],
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.13.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/bitnami/vulndb/tree/main/data/pytorch/BIT-pytorch-2022-45907.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/pytorch/pytorch/commit/767f6aa49fe20a2766b9843d01e3b7f7793df6a3"
		},
		{
			"type": "WEB",
			"url": "https://github.com/pytorch/pytorch/issues/88868"
		}
	],
	"database_specific": {
		"cpes": [
			"cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:*"
		],
		"severity": "Critical"
	}
}
